### ISSUE TITLE
Excluded names are not specific to the directory they were excluded from

### ISSUE THREAD

**Issue by vith** [BouKiCHi/git-exclude#1]
For example:

```console
/tmp/tmp.MSHsL4GFgx
❯ tree
.
├── foo
└── pkg
    └── foo
        └── main.go

3 directories, 1 file
```

Excluding the `foo` file at the top level will also exclude the `pkg/foo` directory's contents. So `main.go` will not show up as a new file in the changes list.

I think the extension should be using paths like `/foo` to avoid this happening, where the leading `/` represents the base directory of the git worktree.

**Comment by BouKiCHi** [comment]
Thank you for the report.
The problem has been fixed.
