### ISSUE TITLE
Does not work if vscode root is not git root

### ISSUE THREAD

**Issue by dantman** [BouKiCHi/git-exclude#3]
I have a project that is part of a big enterprise-ish monolithic repo, so the real project you open in vscode is in a subfolder like `ProjectName.UI.Client`. If you try to use a GitExclude command it fails with `Not git repository.` because GitExclude assumes that the git repository's root is the same as the vscode root.

git commands in the cli, vscode's own source tab, and other git extensions work fine. They all navigate up the tree till they find the real git root.

**Comment by BouKiCHi** [comment]
Thanks, I fixed it to work in the git subdirectory as well.
